# Generated by Django 3.1.2 on 2020-10-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_food',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
