# Generated by Django 3.1.2 on 2020-10-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_fav_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_food',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
