# Generated by Django 3.1.2 on 2020-10-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201008_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_food',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
