# Generated by Django 3.1.2 on 2020-10-14 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20201014_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='like',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
