# Generated by Django 3.1.2 on 2020-10-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20201014_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='create',
            new_name='created',
        ),
    ]
