# Generated by Django 3.1.2 on 2020-10-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20201014_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
    ]
